### PR TITLE
[HEIDELPAYSUPPORT-99] Add Shopware 6.4 compatiblity

### PR DESCRIPTION
**Pull request by JoeKre**

### CODE REVIEW

**Comment by Ruko2010** [comment]
is there an ETA for Compatibility with SW 6.4?

**Review by sixer1182 — CHANGES_REQUESTED** [review]
For Version 2.0.1
* Please update the Version (in composer.json)
* and the Changelogs

**Comment by sixer1182** [comment]
Hi @Ruko2010 
> is there an ETA for Compatibility with SW 6.4?

This is currently in QA and will be the next release.

**Comment by Ruko2010** [comment]
Great. Thank you. I'll watch it 😃

**Pull request merged**
