### PR TITLE
Integration/3.1.0

### PR DESCRIPTION
**Pull request by sobyte**

### CODE REVIEW

**Review by sixer1182 — CHANGES_REQUESTED** [review]
This version constraint does not make sense:
^6.2 || ^6.3 || ^6.4
it is the same as
>=6.2 <7.0 || >=6.3 <7.0 || >=6.4 <7.0

Please review the other comments.

**Comment by sobyte** [comment]
@sixer1182 I've adapted the PR to your comments.

**Review by sixer1182 — COMMENTED** [review]
LGTM, but the version constraints still do not constrict to supported versions.

**Comment by sobyte** [comment]
@sixer1182 I've updated the constraints

**Review by sixer1182 — APPROVED** [review]

**Review by sixer1182 — APPROVED** [review]

**Pull request merged**
